services:
  - type: web
    name: recensito
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:FisicaStatale2024@rujiwukbcoexouvsuyhg.supabase.co:5432/postgres